### ISSUE TITLE
Automatic Unlock before Forget/Prune

### ISSUE THREAD

**Issue by SiddharthManthan** [garethgeorge/backrest#103]
**Is your feature request related to a problem? Please describe.**
- Sometimes a backup process might be interrupted and lock file might not be removed. 
- When the forget/prune is run next time, error is generated. The lock has to manually removed from the repository.

**Describe the solution you'd like**
- Add an option to remove only stale locks (`restic unlock`) before forget/prune runs. 
- This can be opt in. 
- Useful when a single machine backups against single repo (might even work for multiple machines)

References : https://forum.restic.net/t/detecting-stale-locks/1889/25

**Comment by garethgeorge** [comment]
This makes a lot of sense. I'm thinking opt-in is definitely the right approach since, while restic does check lock times and whatnot, it's not strictly speaking safe to automatically run "unlock" especially in cases where multiple clients share a repo.This makes a lot of sense. I'm thinking opt-in is definitely the right approach since, while restic does check lock times and whatnot, it's not strictly speaking safe to automatically run "unlock" especially in cases where multiple clients share a repo.

I imagine this looking something like a simple boolean in the "repo" settings to enable automatic unlock before forget operations?

**Comment by garethgeorge** [comment]
Implemented in https://github.com/garethgeorge/backrest/pull/107 .
