### ISSUE TITLE
Run as root

### ISSUE THREAD

**Issue by jimbolaya** [garethgeorge/backrest#109]
**Is your feature request related to a problem? Please describe.**
The backrest setup doesn't seem to support multi-user *nix systems. Since it runs as root from systemd on Linux by default there are difficulties dealing with ssh keys and access to files. I think the systemd service can be set up for users, but then there would need to be some adjustment for that and I don't know enough systemd to set that up.

**Describe the solution you'd like**
It would be great to have some way to manage multi-user setups or have the user account stuff from the web interface map to users on the the host.

**Additional context**
This looks cool and maybe a solution would be to be able to set this up individual users, as in on different ports.

Anyway, just a start of discussion.

**Comment by garethgeorge** [comment]
This could use better documentation — it should actually be the case that the install script adds a systemd service for whichever user runs the installer. 

If it’s run with sudo this will be root, otherwise the script will use the current user and will ask for sudo for any operations that require it.

**Comment by jimbolaya** [comment]
I realized that after I took a closer look at the script.

Is it possible to have multiple systemd setups so there's something like 

backrest-username.service

There would need to be different ports as well, but that could be spelled out in the install.

I updated my systemd script to include my username which also had my username and it seemed to work fine. I'm sure there's a way to adjust the systemd script for it to use a different port.

Thanks for making this.

**Comment by garethgeorge** [comment]
Sure! I think something of that sort is definitely reasonable (though a bit out of scope for the default installer!). A few things to know:

 1. You can the `BACKREST_PORT` env variable to specify a port per user (and optionally can include a bind interface) e.g. `BACKREST_PORT=127.0.0.1:9001` for one user and `BACKREST_PORT=127.0.0.1:9002` for another.
 2. The backrest binary is installed to /usr/local/bin , this is probably pretty self apparent but you'll want to just stop services and overwrite that binary for any future updates rather than using the update script which may trample any edits you've made to the config.

Glad it's working well for you :)
