### ISSUE TITLE
Small UI issue on long filenames

### ISSUE THREAD

**Issue by dhilgarth** [garethgeorge/backrest#115]
This not just happens with the new item errors but I've also seen it during initial backup when there were files with long names

![image](https://github.com/garethgeorge/backrest/assets/1180105/957d037b-0e10-47a7-876f-523fe6056298)

**Comment by RobProductions** [comment]
Oh I actually get this too now after checking the item errors tab. I believe this can be easily fixed by utilizing the [word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) property in the `ant-collapse-content-box` style (or somewhere else that makes sense, perhaps for all paragraph text?)

I was able to mock this up in Firefox, here's before:

![image](https://github.com/garethgeorge/backrest/assets/11141862/5bd4e762-0521-432e-a9b5-ec70bcaaa945)

And here's after:

![image](https://github.com/garethgeorge/backrest/assets/11141862/6f8c3c65-b7a5-43a0-b6d5-bca94b6e0e3e)

**Comment by garethgeorge** [comment]
I think this should now be fixed by https://github.com/garethgeorge/backrest/pull/191 + some more fixes to overflow handling added in recent releases.
