### ISSUE TITLE
Repo stats show the same number on hover

### ISSUE THREAD

**Issue by ovizii** [garethgeorge/backrest#184]
**Describe the bug**
Repo stats show the same number on mouse-over. This behaviour applies to all 4 graphs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to backrest
2. Click on a repository
3. Click on stats
4. Hover mouse over different data points

**Expected behaviour**
See correct values.

**Screenshots**
![image](https://github.com/garethgeorge/backrest/assets/837902/85bd8cbb-076d-465a-b6a8-d4c4d0c9490b)

![image](https://github.com/garethgeorge/backrest/assets/837902/6e65f6a1-5602-4d79-8183-5f577e4c9579)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Chrome
 - Backrest Version 0.16.0

**Comment by modem** [comment]
In addition, the values on the Y axis are not fully visible for some cases, if the values are more than 5 characters. See Total size and Blob count above. 
In this case, the axis values should be scaled so that the values are readable and meaningful. For example, 100 GB for size, 3*10^5 for blob count.

**Comment by garethgeorge** [comment]
Fixed by migrating to a new chart library in 1.0.0 (with better visuals).
