### ISSUE TITLE
Only backup if not on metered connection

### ISSUE THREAD

**Issue by BiosElement** [garethgeorge/backrest#240]
As I am running Backrest on a laptop, it would be great to have the ability to restrict backups to only non-metered connections.

There are some fairly simple ways to get that information on Linux at least: https://askubuntu.com/questions/711949/set-wifi-as-metered-connection and a possible Windows command: https://gist.github.com/nijave/d657fb4cdb518286942f6c2dd933b472

And a similar project does have a partial workaround: https://github.com/erikw/restic-automatic-backup-scheduler#optional-no-backup-on-metered-connections-linuxsystemd-only

**Comment by garethgeorge** [comment]
Hey, Backrest supports hooks that can support this with a bit of scripting e.g. take a look at https://garethgeorge.github.io/backrest/cookbooks/command-hook-examples#check-for-internet-connectivity

I'm aiming to provide scriptable customization instead of baking in too much by way of backup conditions etc. If you come up with something and want to share it, I'd be very happy to add it to the command hooks cookbook (or answer any questions re: getting a hook working).

**Comment by garethgeorge** [comment]
Going ahead and closing this for now since there's a work around, feel free to open a discussion if you have questions about how to get this set up.
