### ISSUE TITLE
No backup content visible on windows since v1.0.0

### ISSUE THREAD

**Issue by berti34** [garethgeorge/backrest#285]
Hi,
the new release 1.0.0 seems to have a problem on Windows.

As you can see in the screenshots, the content is only shown in version 0.17.2 - even when created with the new release.

**Screenshots**
**Version 1.0.0**
![grafik](https://github.com/garethgeorge/backrest/assets/47418901/30831d4c-51c2-4659-996b-7fff23434d83)

**Version 1.0.0**
![grafik](https://github.com/garethgeorge/backrest/assets/47418901/aff2137d-a94c-4cb0-934c-8da6eaf03fbd)

**Version 0.17.2**
![grafik](https://github.com/garethgeorge/backrest/assets/47418901/18854e6a-ffd2-49e7-b9cb-eb10f0bc7b11)

**Platform Info**
Windows 10

Greetings

**Comment by garethgeorge** [comment]
Thanks for this report! Looking into it, sounds like a bug. There were some changes to the snapshot browser in 1.0.0 but I'm fairly surprised this only surfaces in Windows.

**Comment by garethgeorge** [comment]
Fixed in https://github.com/garethgeorge/backrest/commit/19ed611477186af2702fb7ba403b0bac45ccc4aa , you can download an early release from https://github.com/garethgeorge/backrest/actions/runs/9231534906

**Comment by berti34** [comment]
Great! I can try it tomorrow!
Thanks so much!

**Comment by berti34** [comment]
Hi George!

Works well so far. But the slash as data root is irritating, isn't it?

![image](https://github.com/garethgeorge/backrest/assets/47418901/7c5580a2-5f71-46e8-83a6-a6b3caea3e43)

And restoring works:
![image](https://github.com/garethgeorge/backrest/assets/47418901/eccd20a8-b332-4ec8-b976-bac19b640bcf)

and downloading as TGZ on windows (!) should be changed to ZIP, what do you think?
![image](https://github.com/garethgeorge/backrest/assets/47418901/be73d65d-06f7-4e80-b41c-fe5442ce1835)

**Comment by berti34** [comment]
Works as expected

**Comment by berrnd** [comment]
Hi and first thanks a lot for Backrest!

I just started trying Backrest v1.6.2 on Windows and have exactly this problem there. So far no errors in any logs I can spot - any ideas?

**Comment by berti34** [comment]
Hi, I can't help since I don't have any windows anymore

**Comment by berti34** [comment]
Backrest creates log files. Have you taken a look into?
And always use the latest version.

**Comment by berrnd** [comment]
Thanks for your response @berti34, but I essentially mentioned that already.

> Backrest creates log files. Have you taken a look into?

Sure, and nothing pops up there in the event of expanding the root `/` on the Snapshot Browser (nothing in the Browser Developer Console too, tried on latest Chrome and Firefox).

&nbsp;
> And always use the latest version.

Also self explanatory, v1.6.2 is the latest version as of today and what's published around here.

**Comment by garethgeorge** [comment]
@berrnd there isnt a lot to go on in your report, please include a list of what you’ve tried and what problems you’re seeing. “Nothing visible” isn’t enough to know if you’re seeing a related problem, I suspect this bug is resolved. 

Are you certain your backup is non empty and that you’ve configured paths properly?

**Comment by berrnd** [comment]
Thanks for your response too @garethgeorge.

> there isnt a lot to go on in your report

Well, if there would be more going on, I would have mentioned that front up (not being a noob about creating, solving and reporting software problems generally).

I'm seeing the exact same problem as mentioned initially here above (that's why I replied here instead of opening a new thread). The backup is non empty, backups and all other tasks run fine, just browsing snapshots shows an empty tree:

![grafik](https://github.com/user-attachments/assets/a7248bab-4de0-402c-b46a-7296b20985cd)

![grafik](https://github.com/user-attachments/assets/336e2cb5-9580-4ff3-a29f-65396775132a)

Looking a bit more around at the referenced commit above, I suspect it could be that the source of the affected backup/snapshot is an UNC path, so e.g. `\\share\folder` - `restic ls` output (truncated):

![grafik](https://github.com/user-attachments/assets/3b511c43-4992-4ac8-86ee-6e431859a591)

**Comment by berrnd** [comment]
> Looking a bit more around at the referenced commit above, I suspect it could be about that the source of the affected backup/snapshot is an UNC path

That's definitely the problem and unfortunately there seems to be even more about that in general ([ref1](https://github.com/restic/restic/issues/2807), [ref2](https://github.com/emuell/restic-browser/issues/110#issuecomment-2439716713)).

So I decided to workaround that by utilizing Backrest's command hooks and simply mount the desired UNC path to be backed up as a network drive and then use that drive as the backup source path. Works great since a couple of days and of course also the snapshot browser works using that approach. Thanks again for Backrest, it's a fantastic way to orchestrate restic backups.

Example Plan Config excerpt:
```
"hooks": [
  {
    "conditions": [
      "CONDITION_SNAPSHOT_START"
    ],
    "onError": "ON_ERROR_CANCEL",
    "actionCommand": {
      "command": "net use * /delete /y ; net use B: \\\\server\\share"
    }
  },
  {
    "conditions": [
      "CONDITION_SNAPSHOT_END"
    ],
    "actionCommand": {
      "command": "net use * /delete /y"
    }
  }
]
```

**Comment by garethgeorge** [comment]
Glad you found a workaround here and that it's working well for you :) -- may be worth filing another bug tracking this and related to that restic issue. From my high level read it sounds like there are two issues we'd be tracking

 1. Bug in the listing API 
 2. Bug in the restore API 

not sure if it makes sense for backrest to try to work around these, but we can definitely track the breakage.
