### ISSUE TITLE
Cron Options missing after Update

### ISSUE THREAD

**Issue by InnocentRain** [garethgeorge/backrest#427]
**Describe the bug**
After updating to the 1.4.0 version all cron options other than "Every Month" are missing
![image](https://github.com/user-attachments/assets/c9b71e24-bda5-426f-8609-3c68dfbcb668)

**To Reproduce**
Schedule the Prune Policy to run every week on a specific day

**Expected behavior**
![image](https://github.com/user-attachments/assets/d6d47a9c-647f-42be-b5dc-eda3a79d65e0)
It should look like this, picture is from before the update

**Comment by garethgeorge** [comment]
Thanks for the report -- definitely some bugs here. Made some changes in 1.4.0 to try to reduce the number of options displayed for cron schedules that should typically be infrequent, but I think I was too restrictive in the options I set. Noticing that you can't pick time of day anymore either.

Hiding weekly was an intentional -- but I can see the desire to run e.g. on a specific day such as not in office. I'll bring it back for that use case.

**Comment by garethgeorge** [comment]
This will be fixed in https://github.com/garethgeorge/backrest/commit/cc173aa7b1b9dda10cfb14ca179c9701d15f22f5 , adds back "weekly" and "hourly" scheduling options for "check" and "prune" policies.
