### ISSUE TITLE
Check Policy cron has only months - Add more crons options

### ISSUE THREAD

**Issue by VFansss** [garethgeorge/backrest#441]
**Is your feature request related to a problem? Please describe.**

I'm not sure if it's a bug or a "feature", but when creating/editing a Repository, in "Check Policy" I can only select "month", and in general that check can't be set up at any hh:mm than 0:00

![immagine](https://github.com/user-attachments/assets/e3193c68-3fdb-44e3-b7af-96eb81863f75)

Is quite suboptimal, because I don't what this check (a very long operation) to "overlap" to any backup.

e.g. as you can see above, I've set up a complete 100% check of 2.5TB every 1st of the Month. I can't select anything more in-depth, so it will start at 0 AM. This operation takes ~6-7 hours.

However, this months it would overlap with my backup plan, scheduled every Thursday and Sunday at 6.

Probably isn't anything destructive do both operation at the same time, but not only I don't want to discover by myself but generally speaking probabily would be better have a way to avoid it entirely

**Describe the solution you'd like**

Probably having the same granularity that we have on "Backup schedule" on "Plans" cron  would be more than enough

![immagine](https://github.com/user-attachments/assets/291924c3-bc03-4ed2-8dac-b18ee3e2395f)

**Additional context**

I know that's a stupid thing, but improving the scheduling logic would surely be useful in certain condition.

**Comment by VFansss** [comment]
I've noticed that this is a clone of #427 .

Actually that's a bug, this is a feature.

I don't know what's the right topic to discuss about this 😄

**Comment by garethgeorge** [comment]
Already fixed by some of the misc changes in https://github.com/garethgeorge/backrest/commit/cc173aa7b1b9dda10cfb14ca179c9701d15f22f5 :) 

This change will bring back hourly cron options & day of week scheduling for check and prune operations.

Agreed that this is a regression -- I had meant to remove the super fine grained options for schedules that should be fundamentally infrequent (e.g. check and prune) but took out too much customizability. Previously backrest had supported hourly scheduling for check and prune.

**Comment by garethgeorge** [comment]
Released in 1.5.0!
