### ISSUE TITLE
Ability to add --prune flag to forget operations

### ISSUE THREAD

**Issue by seansheep** [garethgeorge/backrest#449]
**Is your feature request related to a problem? Please describe.**
It would be great to have the option to use restic's --prune flag on forget operations to combine the two steps

**Describe the solution you'd like**
Checkbox to allow prune flag to be used on forget operations for a particular plan. This would probably be an option under the plan's 'retention policy' area.

**Additional context**
See restic --prune flag on forget here:
https://restic.readthedocs.io/en/latest/060_forget.html

**Comment by garethgeorge** [comment]
Backrest aims to be a bit opinionated here :)

Forget and prune are deliberately separate options because backrest is automating by managing command invocations and parsing their output. It helps to have a single consistent way to invoke commands, and it also means I can treat commands individually when parsing their output. As a side note: forget supports JSON summary output but prune doesn't at the moment.

I think it's probably best to keep the operations separate to preserve backrest's operational contract which is largely one operation in the oplog (and viewable in the UI) per restic command run on your behalf.

**Comment by seansheep** [comment]
No worries - Thanks for explanation your reasoning and that's definitely your prerogative.

Is there any neat way to hook a prune invocation on completion of a forget (so as to keep the two invocations discrete)?

**Comment by garethgeorge** [comment]
A variant of https://github.com/garethgeorge/backrest/issues/143 might make sense re: a hook that is able to trigger a backup or prune operation explicitly.

**Comment by seansheep** [comment]
Thanks - That looks like a good option. I'll add a note there.
