### ISSUE TITLE
Failure to ping healthchecks.io hosted locally: dial tcp i/o timeout

### ISSUE THREAD

**Issue by mvantschip** [garethgeorge/backrest#570]
Note: if you have a question or need support please post in the [discussions area](https://github.com/garethgeorge/backrest/discussions).

**Describe the bug**
I am attempting to ping a locally hosted healthchecks.io host URL as a hook, but I receive an error: dial tcp local.url:8000: i/o timeout.

**To Reproduce**

1. Host healthchecks.io locally.
2. Add checks with ping URLs.
3. Aim to use that URL in a healthchecks hook with backrest with `CONDITION_SNAPSHOT_END` (not sure if this matters).
4. Receive failure message upon backup completion.

**Expected behavior**
Healthchecks.io should be pinged after snapshot ends.

**Platform Info**

- Ubuntu Server 24.04.
- Backrest Version 1.6.1.

**Additional context**
Healthchecks.io version 3.7.

**Comment by garethgeorge** [comment]
tcp dial error indicates a network issue, backrest was not able to reach your service at the IP / port / hostname you provided. This is almost always due to an actual issue on the network preventing connectivity rather than a backrest specific problem.

What steps have you taken to diagnose the connection issue / is there anything that makes you think there's a backrest problem at play here?
