### ISSUE TITLE
Fix Azure blob repo config check

### ISSUE THREAD

**Issue by dhilgarth** [garethgeorge/backrest#83]
Right now, Backrest requires `AZURE_ACCOUNT_KEY` when configuring a Azure Blob Repo. However, according to the [documentation](https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#microsoft-azure-blob-storage), both `AZURE_ACCOUNT_KEY` as well as `AZURE_ACCOUNT_SAS` are interchangeably valid.

**Comment by garethgeorge** [comment]
Hmm, backrest forwards environment variables to restic so I'd expect the behavior here to be the same -- would you mind testing with the version of restic used by backrest (0.16.4) and letting me know if you see the same problem there?

**Comment by dhilgarth** [comment]
Sorry for being unclear. What I mean is: I can't create an Azure repo in Backrest with AZURE_ACCOUNT_SAS instead of AZURE_ACCOUNT_KEY. Backrest prevents me from doing so:

![image](https://github.com/garethgeorge/backrest/assets/1180105/e00549fc-38c7-4770-8d62-5b84b5d05a1b)

**Comment by garethgeorge** [comment]
OH. Thanks for clarifying :). 

Looks like this is because I only have the one env var in: https://github.com/garethgeorge/backrest/blob/ebf3d80193963c45c4ddd77ba1be756a7d8a0e12/webui/src/views/AddRepoModal.tsx#L457 . Definitely open to a PR if you'd like to fix this quickly -- otherwise I think you can hack around it by adding the plan manually in the config. Let me know if you're finding yourself blocked. I'll try to get out a fix for it.

**Comment by dhilgarth** [comment]
Done, please check.
