### ISSUE TITLE
Troubleshoot "warning: Partial backup, some files may not have been read completely."

### ISSUE THREAD

**Issue by dhilgarth** [garethgeorge/backrest#86]
For my biggest backup folder (over 3 million files, over 600 GB), I continuously get this warning for each backup:

warning: Partial backup, some files may not have been read completely.

How can I troubleshoot this? What triggers this message?

**Comment by garethgeorge** [comment]
Related issue https://github.com/garethgeorge/backrest/issues/79 , agree that this is definitely something Backrest needs to surface since right now there isn't really a way to identify the missing problem short of copying the command restic runs and finding the problematic folders by running a backup on the cli.

**Comment by dhilgarth** [comment]
But there is no way to actually get the exact command Backrest runs, right?

**Comment by dhilgarth** [comment]
Nevermind, got it from process explorer

**Comment by garethgeorge** [comment]
Added handling for error events in https://github.com/garethgeorge/backrest/commit/caac35a5402d056b626b59d19084d6a699d4346d , will be presented under the backup entry in the UI (along with a warning status as is shown today).

e.g. 
![image](https://github.com/garethgeorge/backrest/assets/7906572/692e1ad0-daed-4183-aacb-3eaa16157bfe)

**Comment by amarendra** [comment]
So as you have already implemented it, I have found the files that were not accessed. 

```
Error on item: ~Library/Mobile Documents/com~apple~CloudDocs
Error on item: ~/Users/amar/Pictures/Photo Booth Library
```

I have given `backrest` Full Disk Access. Should I rather do that for `restic` binary? 

Also I believe `~/Library` folder was easily accessed already for another file and didn't throw an error so is it because of `~` in the path name? (This setup was working in direct `restic` CLI usage).

PS. I have just started using backrest and instead of creating new issues I am commenting on related old issues. I am not sure whether I should create new ones. Or I should rather look in `restic` repo instead of looking here.
