### ISSUE TITLE
Add the possibility to rename a plan and/or repo - Low priority improvement

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#93]
Hi Gareth,

I think it's worth to add the possibility to rename plans and repositories. One should fill that the name chosen initially is not appropriate and wants to rename it.
Currently we can rename plans and repos in the json config file but it has some side effects:
- renaming a plan makes the old plan to live forever in the repository. It's like deleting a plan and creating a new one

Although I find this an interesting feature, I think it's low priority.

**Comment by garethgeorge** [comment]
Hey, it's definitely an a reasonable request but architecturally this is probably won't fix / in-feasible. There are some technical restrictions here

 * the repo ID is referenced by each configured plan which makes changing it relatively unsafe, I'm worried it will introduce more bugs than it adds convenience.
 * the plan ID is used as a tag on each snapshot created by the plan. I suspect that trying to retag snapshots when changing a plan's ID will be fragile / error prone. 

At the moment best bet is to do renaming by manually editing the config, and then deleting the operation log to reset backrest's state.

I think the work around I'll support here in the UI is adding better ways to cleanup and delete backrest's records (e.g. clearing the history of operations for a plan that's been deleted -- this should be made possible without having to delete the whole op log).

**Comment by doxavore** [comment]
Is there a reason the IDs should be user-provided, and not just an opaque value (with some sort of title inside the config)?

**Comment by garethgeorge** [comment]
The IDs are included as tags tags that are set on the snapshots (e.g. formatted as `plan:<plan ID>`), the intent is that they should be human readable and meaningful for the user if the user needs to interact with the repo using the restic cli (instead of backrest) for some reason.

**Comment by RobProductions** [comment]
> the intent is that they should be human readable and meaningful for the user if the user needs to interact with the repo using the restic cli (instead of backrest) for some reason.

That's a good point, but couldn't the original name that the user inputs be used as this ID during creation and then a second value could be used for displaying the plan/repo in the UI? i.e. you store 2 values and then the user is able to customize the second one. 

Alternatively, you could have renaming be a more explicit process where internally it deletes the original plan and makes a new one with the same settings but using the new name. That way the old snapshots will retain the old plan ID and the future snapshots will use the new one. Just some food for thought!

**Comment by garethgeorge** [comment]
Mostly due to the complexity vs value tradeoff it's probably not something I want to add to the UI unless there's a really strong reason. It adds complexity to the logic that associates backrest's datamodel to the backups in your restic repository (which is something I want to keep very simple and reliable so that I can reliably schedule and display operations). 

The supported workaround is to manually rename your plans by editing the config file directly. Your old backups will become disassociated with the renamed plan (and will show up separately under the repo-view in the UI) and can be managed manually using restic commands.

**Comment by Ra72xx** [comment]
May I add that as a simple user not involved in restic/backrest internals it is a bit strange that I'm not able to rename anymore an configuration item in the ui that I created myself? Indeed I thought of a strange ui/browser error and/or a stupid error by myself when I didn't find any "rename" option until I noticed this error report. 
I cannot judge the technical difficulties, but from an end-user perspective I'd strongly vote for user-editable visible names for backup plans. Having to delete complete backups just because of a new name seems a pretty awkward aspect of this (otherwise great!) project.

**Comment by garethgeorge** [comment]
Hey, I agree it's confusing that Backrest doesn't currently set the expectation correctly here -- there isn't a tooltip on the plan ID that would inform a user that this can't be changed. I'll go ahead and add one in the next update.

imo the technical reasons for not supporting this still stand, if you really want to rename a plan doing it manually in the config file (and using a script to update tags on your snapshots) is the correct approach.
